# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Philipp Ludewig"
resume_title:                   "Senior Software Developer Consultant"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "postkasten@philippludewig.de"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "Hamburg • postkasten@philippludewig.de"
display_header_contact_info:    "false"

resume_header_intro: "<p>Experienced software developer and consultant. Fosters healthy teams with an empathetic working style and brings equal amounts of technical proficiency, leadership expertise, and business acumen. Strongly believes in Continuous Delivery.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        false
resume_section_skills:          true
#resume_section_recognition:     false
# resume_section_links:           false
#resume_section_associations:    false
resume_section_interests:       true
resume_section_languages:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/DiesDasJenes"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/philipp-ludewig-8574aa9b/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://blog.philippludewig.de/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
